# typed: strict
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Ens < Formula
  desc "P2P overlay network: QUIC first, relay as fallback"
  homepage "https://github.com/fdaio/enserie"
  url "https://github.com/fdaio/enserie/releases/download/v0.2.9/ens-darwin-arm64.tar.gz"
  version "0.2.9"
  sha256 "318a84800e6e3e43eceffd0536e1ee429145370fdfe3420bcbcb1d424e7e7963"

  def install
    bin.install "ens"
  end

  # Opening a TUN needs root, so the test stays on the one command that does
  # not. A formula whose test needed sudo would fail for every user who runs
  # brew test without it.
  test do
    assert_match version.to_s, shell_output("#{bin}/ens version")
  end
end
