# typed: strict
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Ens < Formula
  desc "P2P overlay network: QUIC first, relay as fallback"
  homepage "https://github.com/fdaio/enserie"
  version "0.2.18"

  on_macos do
    on_arm do
      url "https://github.com/fdaio/enserie/releases/download/v0.2.18/ens-darwin-arm64.tar.gz"
      sha256 "a3c23e2619c18cf2b153fbe68b6fede6b0b040f53058624ef5725cdd1c3cbb8e"
    end

    on_intel do
      url "https://github.com/fdaio/enserie/releases/download/v0.2.18/ens-darwin-amd64.tar.gz"
      sha256 "99b3b7e952f3373c21bbda69fb804f52e910c1b91c236b6278b31a6a73f1daf9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fdaio/enserie/releases/download/v0.2.18/ens-linux-arm64.tar.gz"
      sha256 "314df78f39ceb1748241365a4c194b2f958d1f798fe38847d8044224f71c0be1"
    end

    on_intel do
      url "https://github.com/fdaio/enserie/releases/download/v0.2.18/ens-linux-amd64.tar.gz"
      sha256 "965c3849ad04b07f9a153e7d665b6c34d4a6fc091181fc017256a25c6f6379de"
    end
  end

  def install
    bin.install "ens"
  end

  # Opening a TUN needs root, so the test stays on the one command that does
  # not. A formula whose test needed sudo would fail for every user who runs
  # brew test without it.
  test do
    assert_match version.to_s, shell_output("#{bin}/ens version")
  end
end
