# typed: strict
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Ens < Formula
  desc "P2P overlay network: QUIC first, relay as fallback"
  homepage "https://github.com/fdaio/enserie"
  url "https://github.com/fdaio/enserie/releases/download/v0.2.10/ens-darwin-arm64.tar.gz"
  sha256 "0621228186fa49e56413656038da32432ea015d81950a42efcd25dcc8d8237ac"

  def install
    bin.install "ens"
  end

  # Opening a TUN needs root, so the test stays on the one command that does
  # not. A formula whose test needed sudo would fail for every user who runs
  # brew test without it.
  test do
    assert_match version.to_s, shell_output("#{bin}/ens version")
  end
end
